API1/urls.py
from django.urls import path

from .views import PostList, PostDetail

urlpatterns = [
    path("<int:pk>/", PostDetail.as_view(), name="api_post_detail"),
    path("", PostList.as_view(), name="api_post_list"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("posts/", include("posts.urls")),
    path("api/v1/", include("API1.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/v1/dj-rest-auth/", include("dj_rest_auth.urls")),
    path(
        "api/v1/dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")
    ),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"),name="redoc",), 
    path("api/schema/swagger-ui/",SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui",),
    path("", include("pages.urls")),
]

posts/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(null=True)
    def __str__(self):
        return (self.name)

    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"slug": self.slug})


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category, related_name='categories')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

    @property
    def categories(self):
        return ', '.join([x.name for x in self.category.all()])

class Comment(models.Model): 
    article = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("post_list")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

templates/add_category.html
{% extends 'base.html' %}
{% block title %}Create A New Blog Category!{% endblock %}
{% block content %}

    
{% if user.is_authenticated %}
	<h1>Add Category...</h1>
	<br/><br/>

	<div class="form-group">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-secondary">Add Category</button>
	</div>

{% else %}

You're not allowed here! (and you know it...)

{% endif %}



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Blog App{% endblock title %}</title>
  <meta name="viewport" content="width=device-width,
  initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <header class="p-3 mb-3 border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center
          justify-content-lg-start">
          <a class="navbar-brand" href="{% url 'home' %}">Blog</a>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
            mb-md-0">
          {% if user.is_authenticated %}
            <li><a href="{% url 'post_list' %}" class="nav-link px-2 link-dark">All Posts</a></li>
            <li><a href="{% url 'post_new' %}" class="nav-link px-2 link-dark">Add Post</a></li>
            <li><a href="{% url 'add_category' %}" class="nav-link px-2 link-dark">Add Category</a></li>
            <li><a href="{% url 'category_list' %}" class="nav-link px-2 link-dark">All Categories</a></li>
          </ul>
          <div class="dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
              id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.username }}
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" href="{% url 'password_change'%}">
                Change password</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
            </ul>
          </div>
          {% else %}
          </ul>
          <div class="text-end">
            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
          </div>
          {% endif %}        
        </div>
      </div>
    </header>

    <main>
      {% block content %}
      {% endblock content %}
    </main>
  </div>

  <!-- Bootstrap JavaScript Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/categories.html
{% extends 'base.html' %}

{% block content %}

{% if category_posts %}    

	<h1>{{ cats }}</h1>
	
	<ul>
	{% for post in category_posts %}
		<li>
			<small>
			{% if user.is_authenticated %}	
				<a href="{% url 'post_edit' post.pk %}">(Edit)</a> 
				<a href="{% url 'post_delete' post.pk %}">(Delete)</a>
			{% endif %}
			</small>
		</li>
	{% endfor %}
	</ul>

{% else %}
	<h2>Sorry this page does not exist...</h2>
{% endif %}

{% endblock %}

templates/category_list.html
{% extends "base.html" %}

{% block content %}
{% for category in category_list %}
  <div class="card">
    <div class="card-header">
      <span class="font-weight-bold"><a href="{% url 'category' cats=category.name %}">{{ category.name}}</a></span> &middot;
    </div>
  </div>
{% endfor %}
{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock content %}

templates/post_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ post.title }}"?</p>
  <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="article-entry">
  <h2>{{ object.title }}</h2>
  <p>by {{ object.author }} | {{ object.date }}</p>
  <p>{{ object.body }}</p>
</div>

<hr>
<h4>Comments</h4>
{% for comment in post.comment_set.all %}
  <p>{{ comment.author }} &middot; {{ comment }}</p>
{% endfor %}
<hr>

<h4>Add a comment</h4>
  <form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
  </form>

<p><a href="{% url 'post_edit' post.pk %}">Edit</a> |
  <a href="{% url 'post_delete' post.pk %}">Delete</a></p>
<p>Back to <a href="{% url 'post_list' %}">All Posts</a>.</p>
{% endblock content %}

templates/post_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}

{% block title %}Articles{% endblock title %}

{% block content %}
{% for post in post_list %}
  <div class="card">
    <div class="card-header">
      <span class="font-weight-bold"><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a> |
      </span> &middot;
      <span class="text-muted">by {{ post.author }} |
      {{ post.created_at }}</span>
    </div>
    <div class="card-body">
      <!-- Changes start here! -->
      <p>{{ post.body }}</p>
      <p><a href="">{{ post.categories }}</a></p>
      <a href="{% url 'post_edit' post.pk %}">Edit</a> |
      <a href="{% url 'post_delete' post.pk %}">Delete</a> |
      <a href="{% url 'category_list' %}">Category</a>
    </div>
    <div class="card-footer">
      {% for comment in post.comment_set.all %}
        <p>
          <span class="font-weight-bold">
            {{ comment.author }} &middot;
          </span>
          {{ comment }}
        </p>
      {% endfor %}
    </div>
    <!-- Changes end here! -->
  </div>
  <br/>
{% endfor %}
{% endblock content %}

templates/post_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>New article</h1>
<form action="" method="post">{% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}